import * as React from 'react';
import Head from "next/head";
import { useRouter } from 'next/router'
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import Typography from '@mui/material/Typography';



export default function Board() {
    const {
        query: {type},
    } = useRouter()
    const boardType = () => {
        switch (type){
            case "two-players" : 
            return (
                <Box
                    sx={{
                        width: "100%",
                        height: "100vh",
                        display: 'inline',
                        backgroundColor: "#d9e1e7"
                        }}
                >
                    <Box
                        sx={{
                            width: "100%",
                            height: "10vh",
                            mt: "30px"
                        }} component = {Paper} >
                            <Typography sx={{
                                display: "flex",
                                justifyContent: "center",
                                alignItems: "center",
                                p: 3
                            }}
                            variant = "h4">
                                Bienvenido Elmio
                            </Typography>
                    </Box>
                    <Box
                        sx={{
                            width: "80%",
                            height: "10vh",
                            mt: "30px"
                        }} component = {Paper} >
                            <Typography sx={{
                                display: "",
                                justifyContent: "center",
                                alignItems: "center",
                                p: 3
                            }}
                            variant = "h4">
                                Bienvenido Elmio
                            </Typography>
                    </Box>
                </Box>
            )
            default:
                return (<p>Por Defecto</p>)
        }
    }
    
    return (
        <div>
            <Head>
                <title>Tablero</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {
                    boardType()
                }
            </main>
        </div>
    )
}