import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as React from 'react';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Paper from '@mui/material/Paper';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter();
  const onClickActions = (e, type ) => {
    e.preventDefault;
    router.push("/board/" + type);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box sx={{height: 700, 
                  width: "90%", 
                  backgroundColor: 'gray', 
                  display: 'flex',
                  justifyContent: 'center'}} component={Paper}>
                    <List>
                      <ListItem>
                        <Typography sx={{
                                mt: 5
                            }} variant="h2" component="h1">
                          Bienvenido al Tic Tac Toe
                        </Typography>
                      </ListItem>
                      <ListItem>
                        <Button variant='contained' fullWidth sx={{
                                mt: 5,
                                p: 3
                            }} onClick={(e)=> onClickActions(e, "two-players")}>
                          2 Jugadores
                        </Button>
                      </ListItem>
                      <ListItem>
                        <Button variant='contained' fullWidth sx={{
                                mt: 3,
                                p: 3
                            }} onClick={(e)=> onClickActions(e, "online")}>
                          Online
                        </Button>
                      </ListItem>
                      <ListItem>
                        <Button variant='contained' fullWidth sx={{
                                mt: 3,
                                p: 3
                            }}>
                          Marcador
                        </Button>
                      </ListItem>
                    </List>
        </Box>
      </main>
    </div>
  )
}
